Adds first solution to generating passwords
archanyhm/DevelsAdvocate pull request #46
Opened 2022-02-22 23:32 UTC by Maggonis

Currently only password lenght is decided by user input.

2022-02-23 08:22 UTC, Lakyrea requested changes

2022-02-23 08:22 UTC, Lakyrea commented on src/DevelsAdvocate.Generators/DevelsAdvocate.Generators.csproj
> +        <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
Du hast hier das Projekt mit .NET Framework 4.8 gebaut. Das ist etwas suboptimal, da wir in den anderen Projekten mit .net6 unterwegs sind. Kannst du das noch einmal anpassen ?

2022-02-24 16:40 UTC, Lakyrea approved these changes

2022-02-25 15:09 UTC, archanyhm commented
Großer Umbrau in #57, daher geschlossen

2022-02-25 15:09 UTC, closed without merging