Passwort generator expansions
archanyhm/DevelsAdvocate pull request #57
Opened 2022-02-25 11:11 UTC by Maggonis

2022-02-25 15:24 UTC, archanyhm requested changes

2022-02-25 15:24 UTC, archanyhm commented on src/DevelsAdvocate.CLI/DevelsAdvocate.CLI.csproj
> +      <ProjectReference Include="..\DevelsAdvocate.Generators2\DevelsAdvocate.Generators2.csproj" />
Die muss noch raus, die Generators2 gibbet nicht

2022-02-25 15:24 UTC, archanyhm commented on src/test/DevelsAdvocate.Generators.Test/DevelsAdvocate.Generators.Test.csproj
> +    </ItemGroup>
Hier muss noch "xunit.runners.visualstudio" als Abhängigkeit genutzt werden, weil sonst die Pipeline nicht korrekt testet

2022-02-25 15:54 UTC, archanyhm requested changes

2022-02-25 15:54 UTC, archanyhm commented on src/DevelsAdvocate.Generators/passwordGeneratorService.cs
> +                }
Ich finde nach wie vor die Struktur etwas unschön. Verschachtelte Schleifen sollte man immer bei Möglichkeit vermeiden.

Du könntest schon von vorne herein die ambivalenten Zeichen aus dem `characters`-String rausfiltern. Dann sparst du dir das ganze Do-While-Gedöns.

2022-02-25 15:54 UTC, archanyhm commented on src/test/DevelsAdvocate.Generators.Test/DevelsAdvocate.Generators.Test.csproj
> +    </ItemGroup>
War ich mal so frei, das hinzuzufügen

2022-02-25 16:19 UTC, Lakyrea requested changes
Ich finde die Version schon sehr schön. Hab noch ein paar Kommentare dagelassen. Mein Genörgel hier ist allerdings auf recht hohem Niveau.

2022-02-25 16:19 UTC, Lakyrea commented on src/test/DevelsAdvocate.Generators.Test/PasswordGeneratorServiceTest.cs
> +    public void TestLowercase()
In den Tests wird bisher nur getestet, ob beim auf false setzen von z.B. Lowercase-Charactern, diese wirklich nicht vorhanden sind. Ich vermisse hier das Gegenstück, bei dem nur nur Lowercase-Character ausgewählt sind und auch nur Lowercase-Character vorkommen. Dies gilt für alle Tests, die einen Boolean-Parameter testen.

2022-02-25 16:19 UTC, Lakyrea commented on src/test/DevelsAdvocate.Generators.Test/PasswordGeneratorServiceTest.cs
> +
Ein Test, über den man vielleicht noch nachdenken kann, wäre einer, der die randomness testet, indem man zweimal CreateRandomPassword mit identischen Parametern aufruft und sicherstellt, dass diese nicht identisch sind. Dieser Test wäre minimal flaky, weil ja random zweimal ein identisches Passwort herauskommen könnte, aber das dürfte so selten sein, dass ich die Wahrscheinlichkeit für vernachlässigbar halte.

2022-03-25 07:45 UTC, Lakyrea approved these changes

2022-03-25 07:47 UTC, archanyhm approved these changes

2022-03-25 07:47 UTC, merged